# Generated by Django 3.2.7 on 2022-02-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=255)),
                ('timeStap', models.DateTimeField(blank=True)),
            ],
        ),
    ]
